[services.cdevpc]
type = "sftp"
host = "192.168.0.11"
user = "chester"
port = 22

[services.cdevpc-tailscale]
type = "sftp"
host = "cdevpc-tailscale"
user = "chester"
port = 22

[services.home-pc-lan]
type = "sftp"
host = "192.168.254.105"
user = "cwyark"
port = 22

[services.home-pc-wifi]
type = "sftp"
host = "192.168.14.140"
user = "cwyark"
port = 22
